# Generated by Django 5.0.7 on 2024-08-11 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RAG.file'),
        ),
    ]
